project:
  type: website
  output-dir: docs/

website:
  title: "Richard J. Telford"
  search: true
  repo-url: https://github.com/richardjtelford/richardjtelford.github.io
  navbar:
    background: warning
    left:
      - href: index.qmd
        text: Home
      - collaborate.qmd
      - teaching.qmd
      - research.qmd
      - publications.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/richardjtelford
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/richardjtelford/richardjtelford.github.io/
          - text: Report a Bug
            url:  https://github.com/richardjtelford/richardjtelford.github.io/issues
  page-footer:
    border: true
    center:
    - text: "About"
      href: about.qmd

highlight-style: a11y

format:
  html:
    code-tools: 
      source: true
      toggle: false
      caption: none
    theme: 
      light: [zephyr, css/custom.scss]
      dark: [zephyr, css/dark.scss, css/custom.scss]
    code-link: true
    toc: true

execute: 
  echo: false


