# Employment History

- January 2007 – Present Associate Professor of Plant Ecology. University of Bergen.
- January 2003 – December 2006, Forsker II, Bjerknes Centre for Climate Research.
- September 2001 – December 2002, Research Associate, Newcastle University.
- September 2000 – September 2001, Teaching Fellow, Newcastle University.
- June 2000 – August 2000. Research Associate, Lancaster University. 
- October 1999 – June 2000. Teaching Fellow, Lancaster University. 
- October 1998 – October 1999. Research Associate, Lancaster University.

# Education & Qualifications

2000-2001 Newcastle University, Certificate in Learning and Teaching in Higher Education
1995-1998 University of Wales, Aberystwyth PhD thesis title "Diatom stratigraphies of Lakes Awassa and Tilo, Ethiopia: Holocene records of groundwater variability and climate change." Supervised by Dr H. Lamb.
1991-1994 Clare College, Cambridge University 
  BA (Hons) 2.1 Natural sciences (Plant sciences) Upgraded to MA in 1998 Secondary subjects: Geology and Ecology
